### ISSUE TITLE
Partial connected to input can execute code

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-gui#261]
### Description

It is possible to execute code and get information if a partial is directly connected to an input. Anyone can then write a control in this input to display the data on the client.

### Example of code

```
from taipy.gui import Gui, Markdown
import os
text = ""

md = """
<|toggle|theme|>

# Testing partials

## Enter value:

<|{text}|input|on_change=update_partial|>

## Real text:

<|{repr(text)}|>

## Partial content:

<|part|partial={partial}|>

"""


def update_partial(state, var_name: str, var_value):
    state.partial.update_content(state, state.text)


if __name__ == "__main__":
    gui = Gui(page=Markdown(md))
    partial = gui.add_partial("")
    gui.run(dark_mode=False)

```

**Screenshot**
![temp_partial](https://user-images.githubusercontent.com/98709993/168125650-2c531154-897f-47a3-a135-5314146a13ac.gif)

**Comment by FredLL-Avaiga** [comment]
@FabienLelaquais What would you think of a config property called block_script (default True) that would command the encoding of every string comoing from a user input so that the code demmonstrated here doesn't work anymore ?
Of course we would also have a input property to would allow to override the config value for a specific input.
If you have a better name, I'm all for it ;-)

**Comment by FredLL-Avaiga** [comment]
I'm afraid this doesn't work !
if we modify the value coming from the user input (for ex replace < by &lt;), the input will display the new value ...

**Comment by FredLL-Avaiga** [comment]
I propose to close this issue and add a Nota Bene in the doc about this potential security issue
@FabienLelaquais @FlorianJacta
