### ISSUE TITLE
Gantt charts: "Time passed since 1970-01-01" to specify task duration feels unnatural

### ISSUE THREAD

**Issue by arcanaxion** [Avaiga/taipy-gui#459]
**Description**
Currently, a task duration is specified for Gantt charts as the time passed since the unix epoch -- which feels quite unnatural.

Suggestions:

- Specify an integer, indicating the number of days since the task start date
- Specify a time delta

**Acceptance Criteria**
- [ ] Ensure new code is unit tested, and check code coverage is at least 90%
- [ ] Propagate any change on the demos and run all of them to ensure there is no breaking change
- [ ] Ensure any change is well documented

**Comment by FabienLelaquais** [comment]
So... we do agree that this thing is really cumbersome.
However, that's the way the Plotly library, that we so much depend on, works.
When dealing with bar charts and dates, the setting of the *base* property, which is mandatory for a Gantt-like representation, really is messy.
There's really not much we can do about that. Transforming the data before hand would make no sense since developers, that potentially read Plotly's doc, would get lost.

So what we DID do is clearify, in the doc, why things are the way they are, and how to deal with it.

I hope that [your issue on taipy-doc](https://github.com/Avaiga/taipy-doc/issues/245) will give you the help you want.
In the future, we will add more examples, using multi-trace features.
