### ISSUE TITLE
BUG-text control handling of italics and bold

### ISSUE THREAD

**Issue by FabienLelaquais** [Avaiga/taipy-gui#486]
**Description**

**How to reproduce**

With a Python variable `text` set to any text, the following Taipy markdown does not output a coherent result:
```
Text normal : <|{text}|>.

Text *<|{text}|>*.

Text **<|{text}|>**.
```

The first text appears with a normal font.

The second one in italics.

But the third one, where bold is expected, shows as normal text as well...

**Expected behavior**

The best would be to have a normal text output, then italics then bold.

**Comment by FredLL-Avaiga** [comment]
bold works: the HTML generated is 
`<strong><span class="MuiTypography-root MuiTypography-body1 taipy-text  css-ahj2mt-MuiTypography-root" aria-label="" data-mui-internal-clone-element="true">red</span></strong>`
I guess the problem is with Mui that overrides it ...
strong => font-weight 700
MUI typography => font-weight 400 :-(

it works when specifying the boolean property raw ;-)
ie 
`Text bold: **<|{text}|raw|>**`

Do you validate that workaround @FabienLelaquais ?

**Comment by FredLL-Avaiga** [comment]
I think I might have a solution:
I can unset the font-weight CSS property from the typography this way it can e overridden by the strong tag :-)
